# Generated by Django 5.2.8 on 2025-11-16 14:41

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('reference_period', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('superuser_grants', models.CharField(default='CRUDS', max_length=5)),
                (
                    'admin',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'granted_permissions',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1), default=list, size=None
                    ),
                ),
                ('granted_by_system', models.BooleanField(default=True)),
                (
                    'document',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_simple_dms.document'),
                ),
                (
                    'group',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TagGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=True)),
                (
                    'defaults',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1), default=list, size=None
                    ),
                ),
                ('granted_by_system', models.BooleanField(default=True)),
                (
                    'group',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_simple_dms.documenttag'),
                ),
            ],
        ),
    ]
